image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11.9

environment:
  GITHUB_TOKEN:
    secure: Xq5g5fK58fZaVhOxq4qntYOVT9LEoOAv9T3Reg0ngMvEzaeQfvm4NGrGXtGJ9j/S+efEOwTFuoxzFKQ61mUI53zco/tGEhuZLA0rsssdSNE8zWE410b32jBNhsr6Bd4W

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name counter --icon icon.png --product-name counter --product-version "1.2.3" --copyright "Copyright (c) 2022 YourCompany Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  release: myproduct-v$1
  description: 'proving this thing'
  provider: GitHub
  auth_token:
    secure: Xq5g5fK58fZaVhOxq4qntYOVT9LEoOAv9T3Reg0ngMvEzaeQfvm4NGrGXtGJ9j/S+efEOwTFuoxzFKQ61mUI53zco/tGEhuZLA0rsssdSNE8zWE410b32jBNhsr6Bd4W # your encrypted token from GitHub
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: main                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a counter-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: counter-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf counter-macos.tar.gz -C dist counter.app

  artifacts:
  - path: counter-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf counter-linux.tar.gz -C dist counter

  artifacts:
  - path: counter-linux.tar.gz